### ISSUE TITLE
It is using old juicy-popover v1.2.0, the newest is 2.1.0

### ISSUE THREAD

**Issue by alshakero** [Starcounter/SignIn#165]
It is the reason behind the security warnings.

**Comment by Mihaiii** [comment]
@alshakero I think this was a misunderstanding somewhere.
I wanted to update it, but it was already updated to 2.1.0 in this commit : https://github.com/Starcounter/SignIn/commit/5fb38f9ce729497a5df89bc2bedc6312ef8ea47c .

Could you please confirm?
Do you remember what other apps were you running at that moment? Most probably one of those had 1.2.0 instead of 2.1.0 on the same `sys` path.

**Comment by alshakero** [comment]
Right. But [juicy-popover has it1.2.0 ](https://github.com/Starcounter/SignIn/blob/master/src/SignIn/wwwroot/sys/juicy-popover/package-lock.json). Which threw me off.  Merging https://github.com/Starcounter/SignIn/pull/166 should fix the issue.

**Comment by alshakero** [comment]
Awesome. Merging #166 fixed it.

**Comment by Mihaiii** [comment]
> Awesome. Merging #166 fixed it.
:)

Closing.
